version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=host=postgres-db port=5432 user=postgres dbname=todo_list sslmode=disable password=1234
      - PORT=8080
    depends_on:
      - postgres-db

  postgres-db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: todo_list
    ports:
      - "5433:5432"

  migrate:
    image: migrate/migrate
    depends_on:
      - postgres-db
    volumes:
      - ./internal/db/migrations:/database
    command:
      [ "-path", "/database", "-database",  "postgres://postgres:1234@postgres-db:5432/todo_list?sslmode=disable", "up" ]
