apiVersion: batch/v1
kind: Job
metadata:
  name: db-migration-job
spec:
  template:
    spec:
      containers:
        - name: migrate
          image: migrate/migrate:latest
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: database_url
          command:
            - "sh"
            - "-c"
            - "migrate -path /database -database $DATABASE_URL up"
          volumeMounts:
            - name: migration-files
              mountPath: /database
      volumes:
        - name: migration-files
          configMap:
            name: db-migration-files
      restartPolicy: Never
