apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - name: app
          image: rococo44/todo_list:latest
          ports:
            - containerPort: 8080
          env:
            - name: DATABASE_URL
              value: "host=postgres-db port=5432 user=postgres dbname=todo_list sslmode=disable password=1234"
            - name: PORT
              value: "8080"
      initContainers:
        - name: migrate
          image: migrate/migrate:latest
          command:
            - "migrate"
            - "-path"
            - "/migrations"
            - "-database"
            - "postgres://postgres:1234@postgres-db:5432/todo_list?sslmode=disable"
            - "up"
          volumeMounts:
            - name: migration-files
              mountPath: /migrations
      volumes:
        - name: migration-files
          configMap:
            name: migrations
      restartPolicy: Always