apiVersion: v1
kind: Secret
metadata:
  name: postgres-credentials
type: Opaque
data:
  database_url: cG9zdGdyZXM6Ly9wb3N0Z3JlczoxMjM0QHBvc3RncmVzLWRiOjU0MzIvdG9kb19saXN0P3NzbG1vZGU9ZGlzYWJsZQ==
  database_value: aG9zdD1wb3N0Z3Jlcy1kYiBwb3J0PTU0MzIgdXNlcj1wb3N0Z3JlcyBkYm5hbWU9dG9kb19saXN0IHNzbG1vZGU9ZGlzYWJsZSBwYXNzd29yZD0xMjM0
  database_user: cG9zdGdyZXM=
  database_password: MTIzNA==